flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/tmcdonell/accelerate-blas.git
    commit: 278e1379fc3ca13260f4499f8832fac4863d89fb
  extra-dep: true
extra-deps:
- hedgehog-0.3
- mwc-random-accelerate-0.1.0.0
resolver: nightly-2017-06-19
